### ISSUE TITLE
Broken image reference in rendered documentation

### ISSUE THREAD

**Issue by arska** [projectsyn/component-hub#68]
https://hub.syn.tools/appcat/explanations/crossplane-secrets-non-provider.html references an image at https://hub.syn.tools/appcat/_images/crossplane-secrets.png which does not exist. The original https://github.com/vshn/component-appcat/blob/master/docs/modules/ROOT/pages/explanations/crossplane-secrets-non-provider.adoc references the image at https://github.com/vshn/component-appcat/raw/master/docs/modules/ROOT/pages/explanations/crossplane-secrets.png where it does exist.

**Comment by simu** [comment]
The component-hub itself can't fix this issue, it's up to the individual components to make sure their documentation pages are correct. See https://github.com/vshn/component-appcat/issues/85.
